name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: slax_test
                ports:
                    - 5432:5432
        env:
            MIX_ENV: test
            DATABASE_URL: ecto://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}
        steps:
            # Check out the code
            - name: Check out the code
              uses: actions/checkout@v4

            # Set up Elixir and Erlang/OTP
            - name: Set up Elixir
              uses: erlef/setup-beam@v1
              with:
                  elixir-version: "1.17"
                  otp-version: "27.1.2"

            # Cache dependencies
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: deps
                  key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-mix-

            # Install dependencies
            - name: Install dependencies
              run: mix deps.get

            # Cache Dialyzer PLT files
            - name: Cache Dialyzer PLT
              uses: actions/cache@v3
              with:
                  path: _build/test/*.plt
                  key: ${{ runner.os }}-dialyzer-plt-${{ hashFiles('**/mix.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dialyzer-plt-

            # Set up the database
            - name: Set up the database
              run: mix ecto.create && mix ecto.migrate

            # Run formatter check
            - name: Check formatting
              run: mix format --check-formatted

            # Run Credo for linting
            - name: Run Credo
              run: mix credo --strict

            # Run Sobelow for security analysis
            - name: Run Sobelow
              run: mix sobelow --config

            # Run Dialyzer for type checking
            - name: Run Dialyzer
              run: mix dialyzer
              env:
                  MIX_ENV: dev

            # Run tests
            - name: Run tests
              run: mix test --color
